import type { Metadata } from "next";
import "@/styles/globals.css";
import Nav from "@/components/Navigation/Nav";
import Head from "@/components/Navigation/Head/Head";

export const metadata: Metadata = {
	title: "Acme Laundry Service",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="font-workSans">
				<main className="bg-primary-foreground h-[calc(100vh-56px)]">
					<Head />
					<div className="flex w-full h-full">
						<Nav />
						<div className="w-full overflow-auto max-h-screen">
							{children}
						</div>
					</div>
				</main>
			</body>
		</html>
	);
}
