import type { Metadata } from "next";
import Sidebar from "@/components/Navigation/Sidebar";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import className from "@/styles/RootLayout.module.css";

export const metadata: Metadata = {
	title: "Acme Laundry Service",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<MantineProvider>
					<div id={className.layout_Root}>
						<Sidebar />
						<div className={className.child}>{children}</div>
					</div>
				</MantineProvider>
			</body>
		</html>
	);
}
